# Maintenance Optimization using Operations Research
### Objective
_The objective of this notebook is to optimize transformer maintenance planning using Binary Integer Programming (BIP)._

_The trained Random Forest model is first used to predict the Health Index of every transformer in the dataset._

_The predicted Health Index is then converted into maintenance planning parameters such as maintenance cost, maintenance duration, and crew requirement using predefined planning assumptions._

_Finally, a Binary Integer Programming model selects the optimal set of transformers for maintenance while satisfying limited maintenance resources._

_This notebook demonstrates how Machine Learning and Operations Research can be integrated to support predictive maintenance decision-making in power utilities._

In [29]:
import pandas as pd
import numpy as np
import joblib
from sqlalchemy import create_engine
from pulp import (
    LpProblem,
    LpVariable,
    LpMaximize,
    lpSum,
    LpBinary,
    PULP_CBC_CMD,
    LpStatus
)
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings
warnings.filterwarnings("ignore")

In [30]:
model = joblib.load("../Model/RandomForest_HealthIndex.pkl")
model_feature = joblib.load("../Model/model_features.pkl")

In [31]:
engine = create_engine(
        "postgresql://postgres:Shivam@localhost:5432/transformer_monitoring"
)

In [32]:
query = """
SELECT * FROM transformer_features_final;
"""
df = pd.read_sql(query, engine)
print(f"Total Transformers : {len(df)}")
df.head()

Total Transformers : 470

,Transformer_ID,Hydrogen,Oxigen,Nitrogen,Methane,CO,CO2,Ethylene,Ethane,Acethylene,...,Power factor,Interfacial V,Dielectric rigidity,Water content,Health index,Health_Category,Thermal_Stress_Score,Oil_degradation_score,TDCG,Water_BDV_Ratio
0,TX_1,2845,5860,27842,7406,32,1344,16684,5467,7,...,1.00,45,55,0,30.0,Poor,29557,0.169337,32441,0.000000
1,TX_2,12886,61,25041,877,83,864,4,305,0,...,1.00,45,55,0,30.0,Poor,1186,0.192245,14155,0.000000
2,TX_3,2820,16400,56300,144,257,1080,206,11,2190,...,1.00,39,52,11,30.0,Poor,361,0.211334,5628,0.211538
3,TX_4,1099,70,37520,545,184,1402,6,230,0,...,4.58,33,49,5,58.4,Fair,781,0.336169,2064,0.102041
4,TX_5,3210,3570,47900,160,360,2130,4,43,4,...,0.77,44,55,3,60.0,Fair,207,0.161684,3781,0.054545

Formulate the optimization problem as:                                                   
            max ∑Priorit yixi                                                           
subject to                                                                               
Budget                                                                                   
Maintenance Hours                                                                        
Crew Availability                                                                        
where    xi ∈ {0,1}

### _Prepare Model Input_

In [33]:
X = df[model_feature]
print(X.shape)

(470, 18)

### _Predict Health Index_

In [34]:
df["Predicted_Health_Index"] = model.predict(X)

df["Predicted_Health_Index"] = (
    df["Predicted_Health_Index"].round(2)
)

df[[
    "Transformer_ID", 
    "Predicted_Health_Index"
]].head()

  Transformer_ID  Predicted_Health_Index
0           TX_1                   30.00
1           TX_2                   30.00
2           TX_3                   30.00
3           TX_4                   60.69
4           TX_5                   59.51

### _Create Maintenance Priority Score_
_The maintenance priority score is calculated by combining the predicted Health Index with critical engineering indicators. A weighted scoring approach is adopted to ensure that the optimization model considers both the machine learning prediction and important transformer health characteristics._                                                     
_The following weights are used:_                                                        
- _Predicted Health Index : 60%_
- _TDCG : 20%_
- _Oil Degradation Score : 10%_
- _Thermal Stress Score : 10%_

_A higher priority score indicates a transformer that should receive maintenance earlier._

In [35]:
W_HEALTH = 0.60
W_TDCG = 0.20
W_OIL = 0.10
W_THERMAL = 0.10

# Create scaler 
priority_scaler = MinMaxScaler()

# Normaliza engineering indicators
df[[
    "TDCG_Norm",
    "Oil_Norm", 
    "Thermal_Norm"
]] = priority_scaler.fit_transform(
    df[[
        "TDCG",
        "Oil_degradation_score", 
        "Thermal_Stress_Score"
    ]]
)

# Normalize Health Index 
df["Health_Risk"] = (
    100 - df["Predicted_Health_Index"]
) / 100 
df["Health_Risk"] = (
    df["Health_Risk"].round(2)
)

# Composite Priority Score
df["Priority_Score"] = (
    W_HEALTH * df["Health_Risk"]
    + W_TDCG * df["TDCG_Norm"]
    + W_OIL * df["Oil_Norm"]
    + W_THERMAL * df["Thermal_Norm"]  
)

# Scale to 0-100
df["Priority_Score"] = (
    df["Priority_Score"] * 100 
).round(2)

In [36]:
df[[
    "Transformer_ID",
    "Predicted_Health_Index",
    "Health_Risk",
    "TDCG_Norm",
    "Oil_Norm",
    "Thermal_Norm",
    "Priority_Score"
]].head()

,Transformer_ID,Predicted_Health_Index,Health_Risk,TDCG_Norm,Oil_Norm,Thermal_Norm,Priority_Score
0,TX_1,30.00,0.70,0.798572,0.270225,1.000000,70.67
1,TX_2,30.00,0.70,0.348289,0.323615,0.040126,52.60
2,TX_3,30.00,0.70,0.138316,0.368104,0.012214,48.57
3,TX_4,60.69,0.39,0.050554,0.659053,0.026424,31.27
4,TX_5,59.51,0.40,0.092834,0.252387,0.007003,28.45

### _Assign Predicted Health Category_

In [37]:
def assign_health_category(health_index):
    if health_index >= 90:
        return "Excellent"
    elif health_index >= 70:
        return "Good"
    elif health_index >= 50:
        return "Fair"
    else:
        return "Poor"

df["Predicted_Health_Category"] = (
    df["Predicted_Health_Index"]
    .apply(assign_health_category)
)

df[
    [
        "Transformer_ID",
        "Predicted_Health_Index",
        "Predicted_Health_Category"
    ]
].head()

  Transformer_ID  Predicted_Health_Index Predicted_Health_Category
0           TX_1                   30.00                      Poor
1           TX_2                   30.00                      Poor
2           TX_3                   30.00                      Poor
3           TX_4                   60.69                      Fair
4           TX_5                   59.51                      Fair

### _Filter Transformers for Maintenance Planning_
_From both an engineering and optimization perspective, Excellent transformers do not require corrective or preventive maintenance in the current planning cycle. Including them in the optimization only increases the problem size without adding value._

In [38]:
optimization_df = df[
    df["Predicted_Health_Category"] != "Excellent"
].copy()

print(f"Total Transformers           : {len(df)}")
print(f"Excellent Transformers       : {(df['Predicted_Health_Category'] == 'Excellent').sum()}")
print(f"Transformers for Optimization: {len(optimization_df)}")
print("=" * 50)
print(f"Excellent Transformers need Routine Monitoring Only")

Total Transformers           : 470
Excellent Transformers       : 345
Transformers for Optimization: 125
==================================================
Excellent Transformers need Routine Monitoring Only

### _Create Planning Assumptions_

In [39]:
planning_parameters = pd.DataFrame({

    "Predicted_Health_Category": [
        "Excellent",
        "Good",
        "Fair",
        "Poor"
    ],

    "Maintenance_Cost": [
        0,
        20000,
        50000,
        90000
    ],

    "Maintenance_Hours": [
        0,
        3,
        8,
        16
    ],

    "Crew_Required": [
        0,
        2,
        3,
        4
    ]

})

planning_parameters

,Predicted_Health_Category,Maintenance_Cost,Maintenance_Hours,Crew_Required
0,Excellent,0,0,0
1,Good,20000,3,2
2,Fair,50000,8,3
3,Poor,90000,16,4

### _Merge Planning Parameters_

In [65]:
# Merge planning parameters
df = df.merge(
    planning_parameters,
    on="Predicted_Health_Category",
    how="left"
)

# NOW create optimization dataframe
optimization_df = df[
    df["Predicted_Health_Category"] != "Excellent"
].copy()

In [66]:
df[
    [
        "Transformer_ID",
        "Predicted_Health_Index",
        "Predicted_Health_Category",
        "Priority_Score",
        "Maintenance_Cost",
        "Maintenance_Hours",
        "Crew_Required"
    ]
].head(10)

,Transformer_ID,Predicted_Health_Index,Predicted_Health_Category,Priority_Score,Maintenance_Cost,Maintenance_Hours,Crew_Required
0,TX_1,30.00,Poor,70.67,90000,16,4
1,TX_2,30.00,Poor,52.60,90000,16,4
2,TX_3,30.00,Poor,48.57,90000,16,4
3,TX_4,60.69,Fair,31.27,50000,8,3
4,TX_5,59.51,Fair,28.45,50000,8,3
5,TX_6,30.00,Poor,56.41,90000,16,4
6,TX_7,30.00,Poor,50.29,90000,16,4
7,TX_8,95.10,Excellent,4.56,0,0,0
8,TX_9,88.14,Good,13.25,20000,3,2
9,TX_10,91.18,Excellent,11.00,0,0,0

## Build Binary Integer Programming Model

This section formulates the transformer maintenance planning problem as a Binary Integer Programming (BIP) model.

The objective is to maximize the overall maintenance priority while considering limited maintenance resources.

#### Decision Variable

For each transformer:

- **xᵢ = 1** → Transformer is selected for maintenance.
- **xᵢ = 0** → Transformer is not selected for maintenance.

#### Objective

Maximize the total maintenance priority score.

#### Constraints

The optimization model considers:

- Maintenance Budget
- Available Maintenance Hours
- Available Maintenance Crew

The solution identifies the optimal subset of transformers that should be maintained during the current planning period.

#### _Planning Assumptions_

In [67]:
MAINTENANCE_BUDGET = 350000      # ₹
AVAILABLE_HOURS = 70             # Hours
AVAILABLE_CREW = 17              # Total Crew Members

print("Planning Constraints")
print("-"*35)
print(f"Maintenance Budget : ₹{MAINTENANCE_BUDGET:,}")
print(f"Available Hours    : {AVAILABLE_HOURS}")
print(f"Available Crew     : {AVAILABLE_CREW}")

Planning Constraints
-----------------------------------
Maintenance Budget : ₹350,000
Available Hours    : 70
Available Crew     : 17

#### _Create Optimization Model_
_Using LpMaximize because we want to maximize ∑Priorityi​xi​                             
The selected transformers should provide the maximum overall maintenance benefit._

In [69]:
maintenance_model = LpProblem(
    name="Transformer_Maintenance_Optimization",
    sense=LpMaximize
)

print("Optimization model created successfully.")

Optimization model created successfully.

### _Decision Variables_

In [70]:
decision_variables = {
    transformer_id: LpVariable(
        name=f"x_{transformer_id}",
        cat=LpBinary
    )
    for transformer_id in optimization_df["Transformer_ID"]
}

print(f"Decision Variables Created : {len(decision_variables)}")

Decision Variables Created : 125

### _Objective Function_
maxi=∑Priorityi × xi​

In [71]:
maintenance_model += lpSum(
    decision_variables[row["Transformer_ID"]]
    *
    row["Priority_Score"]
    for _, row in optimization_df.iterrows()
), "Maximize_Total_Priority"

### _Budget Constraint_
∑Costi​xi​≤Budget

In [72]:
maintenance_model += (
    lpSum(
        decision_variables[row["Transformer_ID"]]
        *
        row["Maintenance_Cost"]
        for _, row in optimization_df.iterrows()

    ) <=  MAINTENANCE_BUDGET

), "Budget_Constraint"

### _Maintenance Hours Constraint_
∑Hoursi​xi​ ≤ AvailableHours

In [73]:
maintenance_model += (
   
    lpSum(
        decision_variables[row["Transformer_ID"]]
        *
        row["Maintenance_Hours"]
        for _, row in optimization_df.iterrows()
    ) <=  AVAILABLE_HOURS

), "Hours_Constraint"

### _Crew Constraint_
∑Crewi​xi​ ≤ AvailableCrew

In [74]:
maintenance_model += (
    
    lpSum(
        decision_variables[row["Transformer_ID"]]
        *
        row["Crew_Required"]
        for _, row in optimization_df.iterrows()
    ) <= AVAILABLE_CREW

), "Crew_Constraint"

In [75]:
print(maintenance_model)

Transformer_Maintenance_Optimization:
MAXIMIZE
70.67*x_TX_1 + 11.86*x_TX_103 + 13.87*x_TX_106 + 19.5*x_TX_110 + 14.28*x_TX_113 + 28.32*x_TX_115 + 12.82*x_TX_116 + 15.66*x_TX_117 + 19.61*x_TX_118 + 15.05*x_TX_121 + 15.42*x_TX_123 + 16.44*x_TX_124 + 17.02*x_TX_13 + 16.33*x_TX_135 + 16.61*x_TX_139 + 66.79*x_TX_14 + 13.12*x_TX_145 + 15.76*x_TX_149 + 58.92*x_TX_15 + 69.06*x_TX_16 + 63.41*x_TX_17 + 15.75*x_TX_175 + 15.52*x_TX_177 + 15.39*x_TX_178 + 12.05*x_TX_179 + 55.33*x_TX_18 + 31.44*x_TX_184 + 11.74*x_TX_186 + 51.44*x_TX_19 + 14.22*x_TX_198 + 52.6*x_TX_2 + 57.16*x_TX_20 + 11.54*x_TX_201 + 17.62*x_TX_204 + 12.03*x_TX_205 + 28.7*x_TX_21 + 13.09*x_TX_211 + 16.33*x_TX_212 + 11.92*x_TX_216 + 51.61*x_TX_22 + 10.74*x_TX_220 + 19.16*x_TX_23 + 16.1*x_TX_230 + 13.49*x_TX_235 + 11.49*x_TX_236 + 10.82*x_TX_238 + 23.82*x_TX_24 + 11.54*x_TX_243 + 11.68*x_TX_246 + 11.53*x_TX_248 + 13.9*x_TX_25 + 11.89*x_TX_257 + 19.68*x_TX_26 + 15.35*x_TX_263 + 13.21*x_TX_264 + 22.2*x_TX_27 + 11.58*x_TX_270 + 11.27*x_TX_277 + 51.78*x_TX_28 + 23.06*x_TX_29 + 15.45*x_TX_290 + 17.08*x_TX_293 + 12.57*x_TX_294 + 15.08*x_TX_297 + 48.57*x_TX_3 + 11.19*x_TX_311 + 12.87*x_TX_312 + 15.54*x_TX_316 + 12.73*x_TX_327 + 14.82*x_TX_328 + 16.76*x_TX_332 + 13.59*x_TX_334 + 12.68*x_TX_336 + 15.66*x_TX_345 + 28.25*x_TX_35 + 11.49*x_TX_353 + 16.12*x_TX_359 + 51.99*x_TX_36 + 16.42*x_TX_362 + 12.67*x_TX_364 + 52.09*x_TX_37 + 16.43*x_TX_371 + 16.42*x_TX_375 + 16.2*x_TX_377 + 16.68*x_TX_38 + 13.27*x_TX_384 + 56.08*x_TX_39 + 12.74*x_TX_394 + 16.68*x_TX_395 + 31.27*x_TX_4 + 54.44*x_TX_40 + 37.6*x_TX_41 + 51.18*x_TX_42 + 50.06*x_TX_43 + 16.17*x_TX_44 + 50.4*x_TX_45 + 11.23*x_TX_450 + 11.3*x_TX_452 + 10.7*x_TX_454 + 12.72*x_TX_455 + 30.38*x_TX_46 + 11.95*x_TX_462 + 47.83*x_TX_47 + 31.4*x_TX_48 + 29.1*x_TX_49 + 28.45*x_TX_5 + 13.4*x_TX_50 + 10.14*x_TX_51 + 19.02*x_TX_53 + 16.57*x_TX_54 + 18.4*x_TX_55 + 56.41*x_TX_6 + 11.52*x_TX_62 + 13.68*x_TX_64 + 15.24*x_TX_65 + 18.46*x_TX_69 + 50.29*x_TX_7 + 12.77*x_TX_72 + 13.66*x_TX_76 + 12.57*x_TX_80 + 15.35*x_TX_85 + 12.32*x_TX_86 + 15.6*x_TX_88 + 13.25*x_TX_9 + 12.21*x_TX_98 + 0.0
SUBJECT TO
Budget_Constraint: 90000 x_TX_1 + 20000 x_TX_103 + 20000 x_TX_106
 + 20000 x_TX_110 + 20000 x_TX_113 + 50000 x_TX_115 + 20000 x_TX_116
 + 20000 x_TX_117 + 20000 x_TX_118 + 20000 x_TX_121 + 20000 x_TX_123
 + 20000 x_TX_124 + 20000 x_TX_13 + 20000 x_TX_135 + 20000 x_TX_139
 + 90000 x_TX_14 + 20000 x_TX_145 + 20000 x_TX_149 + 90000 x_TX_15
 + 90000 x_TX_16 + 90000 x_TX_17 + 20000 x_TX_175 + 20000 x_TX_177
 + 20000 x_TX_178 + 20000 x_TX_179 + 90000 x_TX_18 + 50000 x_TX_184
 + 20000 x_TX_186 + 90000 x_TX_19 + 20000 x_TX_198 + 90000 x_TX_2
 + 90000 x_TX_20 + 20000 x_TX_201 + 20000 x_TX_204 + 20000 x_TX_205
 + 50000 x_TX_21 + 20000 x_TX_211 + 20000 x_TX_212 + 20000 x_TX_216
 + 90000 x_TX_22 + 20000 x_TX_220 + 20000 x_TX_23 + 20000 x_TX_230
 + 20000 x_TX_235 + 20000 x_TX_236 + 20000 x_TX_238 + 20000 x_TX_24
 + 20000 x_TX_243 + 20000 x_TX_246 + 20000 x_TX_248 + 20000 x_TX_25
 + 20000 x_TX_257 + 20000 x_TX_26 + 20000 x_TX_263 + 20000 x_TX_264
 + 20000 x_TX_27 + 20000 x_TX_270 + 20000 x_TX_277 + 90000 x_TX_28
 + 20000 x_TX_29 + 20000 x_TX_290 + 20000 x_TX_293 + 20000 x_TX_294
 + 20000 x_TX_297 + 90000 x_TX_3 + 20000 x_TX_311 + 20000 x_TX_312
 + 20000 x_TX_316 + 20000 x_TX_327 + 20000 x_TX_328 + 20000 x_TX_332
 + 20000 x_TX_334 + 20000 x_TX_336 + 20000 x_TX_345 + 50000 x_TX_35
 + 20000 x_TX_353 + 20000 x_TX_359 + 90000 x_TX_36 + 20000 x_TX_362
 + 20000 x_TX_364 + 90000 x_TX_37 + 20000 x_TX_371 + 20000 x_TX_375
 + 20000 x_TX_377 + 20000 x_TX_38 + 20000 x_TX_384 + 90000 x_TX_39
 + 20000 x_TX_394 + 20000 x_TX_395 + 50000 x_TX_4 + 90000 x_TX_40
 + 50000 x_TX_41 + 90000 x_TX_42 + 90000 x_TX_43 + 20000 x_TX_44
 + 90000 x_TX_45 + 20000 x_TX_450 + 20000 x_TX_452 + 20000 x_TX_454
 + 20000 x_TX_455 + 50000 x_TX_46 + 20000 x_TX_462 + 90000 x_TX_47
 + 50000 x_TX_48 + 50000 x_TX_49 + 50000 x_TX_5 + 20000 x_TX_50
 + 20000 x_TX_51 + 20000 x_TX_53 + 20000 x_TX_54 + 20000 x_TX_55
 + 90000 x_TX_6 + 20000 x_TX_62 + 20000 x_TX_64 + 20000 x_TX_65
 + 20000 x_TX_69 + 90000 x_TX_7 + 20000 x_TX_72 + 20000 x_TX_76
 + 20000 x_TX_80 + 20000 x_TX_85 + 20000 x_TX_86 + 20000 x_TX_88
 + 20000 x_TX_9 + 20000 x_TX_98 <= 350000

Hours_Constraint: 16 x_TX_1 + 3 x_TX_103 + 3 x_TX_106 + 3 x_TX_110
 + 3 x_TX_113 + 8 x_TX_115 + 3 x_TX_116 + 3 x_TX_117 + 3 x_TX_118 + 3 x_TX_121
 + 3 x_TX_123 + 3 x_TX_124 + 3 x_TX_13 + 3 x_TX_135 + 3 x_TX_139 + 16 x_TX_14
 + 3 x_TX_145 + 3 x_TX_149 + 16 x_TX_15 + 16 x_TX_16 + 16 x_TX_17 + 3 x_TX_175
 + 3 x_TX_177 + 3 x_TX_178 + 3 x_TX_179 + 16 x_TX_18 + 8 x_TX_184 + 3 x_TX_186
 + 16 x_TX_19 + 3 x_TX_198 + 16 x_TX_2 + 16 x_TX_20 + 3 x_TX_201 + 3 x_TX_204
 + 3 x_TX_205 + 8 x_TX_21 + 3 x_TX_211 + 3 x_TX_212 + 3 x_TX_216 + 16 x_TX_22
 + 3 x_TX_220 + 3 x_TX_23 + 3 x_TX_230 + 3 x_TX_235 + 3 x_TX_236 + 3 x_TX_238
 + 3 x_TX_24 + 3 x_TX_243 + 3 x_TX_246 + 3 x_TX_248 + 3 x_TX_25 + 3 x_TX_257
 + 3 x_TX_26 + 3 x_TX_263 + 3 x_TX_264 + 3 x_TX_27 + 3 x_TX_270 + 3 x_TX_277
 + 16 x_TX_28 + 3 x_TX_29 + 3 x_TX_290 + 3 x_TX_293 + 3 x_TX_294 + 3 x_TX_297
 + 16 x_TX_3 + 3 x_TX_311 + 3 x_TX_312 + 3 x_TX_316 + 3 x_TX_327 + 3 x_TX_328
 + 3 x_TX_332 + 3 x_TX_334 + 3 x_TX_336 + 3 x_TX_345 + 8 x_TX_35 + 3 x_TX_353
 + 3 x_TX_359 + 16 x_TX_36 + 3 x_TX_362 + 3 x_TX_364 + 16 x_TX_37 + 3 x_TX_371
 + 3 x_TX_375 + 3 x_TX_377 + 3 x_TX_38 + 3 x_TX_384 + 16 x_TX_39 + 3 x_TX_394
 + 3 x_TX_395 + 8 x_TX_4 + 16 x_TX_40 + 8 x_TX_41 + 16 x_TX_42 + 16 x_TX_43
 + 3 x_TX_44 + 16 x_TX_45 + 3 x_TX_450 + 3 x_TX_452 + 3 x_TX_454 + 3 x_TX_455
 + 8 x_TX_46 + 3 x_TX_462 + 16 x_TX_47 + 8 x_TX_48 + 8 x_TX_49 + 8 x_TX_5
 + 3 x_TX_50 + 3 x_TX_51 + 3 x_TX_53 + 3 x_TX_54 + 3 x_TX_55 + 16 x_TX_6
 + 3 x_TX_62 + 3 x_TX_64 + 3 x_TX_65 + 3 x_TX_69 + 16 x_TX_7 + 3 x_TX_72
 + 3 x_TX_76 + 3 x_TX_80 + 3 x_TX_85 + 3 x_TX_86 + 3 x_TX_88 + 3 x_TX_9
 + 3 x_TX_98 <= 70

Crew_Constraint: 4 x_TX_1 + 2 x_TX_103 + 2 x_TX_106 + 2 x_TX_110 + 2 x_TX_113
 + 3 x_TX_115 + 2 x_TX_116 + 2 x_TX_117 + 2 x_TX_118 + 2 x_TX_121 + 2 x_TX_123
 + 2 x_TX_124 + 2 x_TX_13 + 2 x_TX_135 + 2 x_TX_139 + 4 x_TX_14 + 2 x_TX_145
 + 2 x_TX_149 + 4 x_TX_15 + 4 x_TX_16 + 4 x_TX_17 + 2 x_TX_175 + 2 x_TX_177
 + 2 x_TX_178 + 2 x_TX_179 + 4 x_TX_18 + 3 x_TX_184 + 2 x_TX_186 + 4 x_TX_19
 + 2 x_TX_198 + 4 x_TX_2 + 4 x_TX_20 + 2 x_TX_201 + 2 x_TX_204 + 2 x_TX_205
 + 3 x_TX_21 + 2 x_TX_211 + 2 x_TX_212 + 2 x_TX_216 + 4 x_TX_22 + 2 x_TX_220
 + 2 x_TX_23 + 2 x_TX_230 + 2 x_TX_235 + 2 x_TX_236 + 2 x_TX_238 + 2 x_TX_24
 + 2 x_TX_243 + 2 x_TX_246 + 2 x_TX_248 + 2 x_TX_25 + 2 x_TX_257 + 2 x_TX_26
 + 2 x_TX_263 + 2 x_TX_264 + 2 x_TX_27 + 2 x_TX_270 + 2 x_TX_277 + 4 x_TX_28
 + 2 x_TX_29 + 2 x_TX_290 + 2 x_TX_293 + 2 x_TX_294 + 2 x_TX_297 + 4 x_TX_3
 + 2 x_TX_311 + 2 x_TX_312 + 2 x_TX_316 + 2 x_TX_327 + 2 x_TX_328 + 2 x_TX_332
 + 2 x_TX_334 + 2 x_TX_336 + 2 x_TX_345 + 3 x_TX_35 + 2 x_TX_353 + 2 x_TX_359
 + 4 x_TX_36 + 2 x_TX_362 + 2 x_TX_364 + 4 x_TX_37 + 2 x_TX_371 + 2 x_TX_375
 + 2 x_TX_377 + 2 x_TX_38 + 2 x_TX_384 + 4 x_TX_39 + 2 x_TX_394 + 2 x_TX_395
 + 3 x_TX_4 + 4 x_TX_40 + 3 x_TX_41 + 4 x_TX_42 + 4 x_TX_43 + 2 x_TX_44
 + 4 x_TX_45 + 2 x_TX_450 + 2 x_TX_452 + 2 x_TX_454 + 2 x_TX_455 + 3 x_TX_46
 + 2 x_TX_462 + 4 x_TX_47 + 3 x_TX_48 + 3 x_TX_49 + 3 x_TX_5 + 2 x_TX_50
 + 2 x_TX_51 + 2 x_TX_53 + 2 x_TX_54 + 2 x_TX_55 + 4 x_TX_6 + 2 x_TX_62
 + 2 x_TX_64 + 2 x_TX_65 + 2 x_TX_69 + 4 x_TX_7 + 2 x_TX_72 + 2 x_TX_76
 + 2 x_TX_80 + 2 x_TX_85 + 2 x_TX_86 + 2 x_TX_88 + 2 x_TX_9 + 2 x_TX_98 <= 17

VARIABLES
0 <= x_TX_1 <= 1 Integer
0 <= x_TX_103 <= 1 Integer
0 <= x_TX_106 <= 1 Integer
0 <= x_TX_110 <= 1 Integer
0 <= x_TX_113 <= 1 Integer
0 <= x_TX_115 <= 1 Integer
0 <= x_TX_116 <= 1 Integer
0 <= x_TX_117 <= 1 Integer
0 <= x_TX_118 <= 1 Integer
0 <= x_TX_121 <= 1 Integer
0 <= x_TX_123 <= 1 Integer
0 <= x_TX_124 <= 1 Integer
0 <= x_TX_13 <= 1 Integer
0 <= x_TX_135 <= 1 Integer
0 <= x_TX_139 <= 1 Integer
0 <= x_TX_14 <= 1 Integer
0 <= x_TX_145 <= 1 Integer
0 <= x_TX_149 <= 1 Integer
0 <= x_TX_15 <= 1 Integer
0 <= x_TX_16 <= 1 Integer
0 <= x_TX_17 <= 1 Integer
0 <= x_TX_175 <= 1 Integer
0 <= x_TX_177 <= 1 Integer
0 <= x_TX_178 <= 1 Integer
0 <= x_TX_179 <= 1 Integer
0 <= x_TX_18 <= 1 Integer
0 <= x_TX_184 <= 1 Integer
0 <= x_TX_186 <= 1 Integer
0 <= x_TX_19 <= 1 Integer
0 <= x_TX_198 <= 1 Integer
0 <= x_TX_2 <= 1 Integer
0 <= x_TX_20 <= 1 Integer
0 <= x_TX_201 <= 1 Integer
0 <= x_TX_204 <= 1 Integer
0 <= x_TX_205 <= 1 Integer
0 <= x_TX_21 <= 1 Integer
0 <= x_TX_211 <= 1 Integer
0 <= x_TX_212 <= 1 Integer
0 <= x_TX_216 <= 1 Integer
0 <= x_TX_22 <= 1 Integer
0 <= x_TX_220 <= 1 Integer
0 <= x_TX_23 <= 1 Integer
0 <= x_TX_230 <= 1 Integer
0 <= x_TX_235 <= 1 Integer
0 <= x_TX_236 <= 1 Integer
0 <= x_TX_238 <= 1 Integer
0 <= x_TX_24 <= 1 Integer
0 <= x_TX_243 <= 1 Integer
0 <= x_TX_246 <= 1 Integer
0 <= x_TX_248 <= 1 Integer
0 <= x_TX_25 <= 1 Integer
0 <= x_TX_257 <= 1 Integer
0 <= x_TX_26 <= 1 Integer
0 <= x_TX_263 <= 1 Integer
0 <= x_TX_264 <= 1 Integer
0 <= x_TX_27 <= 1 Integer
0 <= x_TX_270 <= 1 Integer
0 <= x_TX_277 <= 1 Integer
0 <= x_TX_28 <= 1 Integer
0 <= x_TX_29 <= 1 Integer
0 <= x_TX_290 <= 1 Integer
0 <= x_TX_293 <= 1 Integer
0 <= x_TX_294 <= 1 Integer
0 <= x_TX_297 <= 1 Integer
0 <= x_TX_3 <= 1 Integer
0 <= x_TX_311 <= 1 Integer
0 <= x_TX_312 <= 1 Integer
0 <= x_TX_316 <= 1 Integer
0 <= x_TX_327 <= 1 Integer
0 <= x_TX_328 <= 1 Integer
0 <= x_TX_332 <= 1 Integer
0 <= x_TX_334 <= 1 Integer
0 <= x_TX_336 <= 1 Integer
0 <= x_TX_345 <= 1 Integer
0 <= x_TX_35 <= 1 Integer
0 <= x_TX_353 <= 1 Integer
0 <= x_TX_359 <= 1 Integer
0 <= x_TX_36 <= 1 Integer
0 <= x_TX_362 <= 1 Integer
0 <= x_TX_364 <= 1 Integer
0 <= x_TX_37 <= 1 Integer
0 <= x_TX_371 <= 1 Integer
0 <= x_TX_375 <= 1 Integer
0 <= x_TX_377 <= 1 Integer
0 <= x_TX_38 <= 1 Integer
0 <= x_TX_384 <= 1 Integer
0 <= x_TX_39 <= 1 Integer
0 <= x_TX_394 <= 1 Integer
0 <= x_TX_395 <= 1 Integer
0 <= x_TX_4 <= 1 Integer
0 <= x_TX_40 <= 1 Integer
0 <= x_TX_41 <= 1 Integer
0 <= x_TX_42 <= 1 Integer
0 <= x_TX_43 <= 1 Integer
0 <= x_TX_44 <= 1 Integer
0 <= x_TX_45 <= 1 Integer
0 <= x_TX_450 <= 1 Integer
0 <= x_TX_452 <= 1 Integer
0 <= x_TX_454 <= 1 Integer
0 <= x_TX_455 <= 1 Integer
0 <= x_TX_46 <= 1 Integer
0 <= x_TX_462 <= 1 Integer
0 <= x_TX_47 <= 1 Integer
0 <= x_TX_48 <= 1 Integer
0 <= x_TX_49 <= 1 Integer
0 <= x_TX_5 <= 1 Integer
0 <= x_TX_50 <= 1 Integer
0 <= x_TX_51 <= 1 Integer
0 <= x_TX_53 <= 1 Integer
0 <= x_TX_54 <= 1 Integer
0 <= x_TX_55 <= 1 Integer
0 <= x_TX_6 <= 1 Integer
0 <= x_TX_62 <= 1 Integer
0 <= x_TX_64 <= 1 Integer
0 <= x_TX_65 <= 1 Integer
0 <= x_TX_69 <= 1 Integer
0 <= x_TX_7 <= 1 Integer
0 <= x_TX_72 <= 1 Integer
0 <= x_TX_76 <= 1 Integer
0 <= x_TX_80 <= 1 Integer
0 <= x_TX_85 <= 1 Integer
0 <= x_TX_86 <= 1 Integer
0 <= x_TX_88 <= 1 Integer
0 <= x_TX_9 <= 1 Integer
0 <= x_TX_98 <= 1 Integer

## Solve the Binary Integer Programming Model

This section solves the Binary Integer Programming (BIP) model using the CBC solver provided by PuLP.

The solver determines the optimal set of transformers to maintain while satisfying the resource constraints on:

- Maintenance Budget
- Maintenance Hours
- Available Maintenance Crew

The resulting maintenance plan maximizes the total maintenance priority score.

### _Solve the Model_

In [79]:
solver = PULP_CBC_CMD(msg=False)

maintenance_model.solve(solver)

print("Optimization Status :", LpStatus[maintenance_model.status])

Optimization Status : Optimal

_Use PULP_CBC_CMD() to calls the CBC solver (the default open-source solver bundled with PuLP).                                                                                   
Use msg=False to hides the detailed solver log. During debugging, you can set msg=True.  
Use maintenance_model.solve() to sends the objective function and constraints to the solver._

### _Store Decision Variables_

In [81]:
optimization_df["Maintenance_Selected"] = optimization_df["Transformer_ID"].apply(
    lambda transformer:
    int(decision_variables[transformer].varValue)
)

optimization_df[
    [
        "Transformer_ID",
        "Priority_Score",
        "Maintenance_Selected"
    ]
].head()

  Transformer_ID  Priority_Score  Maintenance_Selected
0           TX_1           70.67                     1
1           TX_2           52.60                     0
2           TX_3           48.57                     0
3           TX_4           31.27                     0
4           TX_5           28.45                     0

### _Create Optimal Maintenance Schedule_

In [82]:
maintenance_schedule = (
    optimization_df[
        optimization_df["Maintenance_Selected"] == 1
        ].sort_values(
        by="Priority_Score",
        ascending=False
    ).reset_index(drop=True)
)

maintenance_schedule.head()

,Transformer_ID,Hydrogen,Oxigen,Nitrogen,Methane,CO,CO2,Ethylene,Ethane,Acethylene,...,Maintenance_Cost_x,Maintenance_Hours_x,Crew_Required_x,Maintenance_Cost_y,Maintenance_Hours_y,Crew_Required_y,Maintenance_Cost,Maintenance_Hours,Crew_Required,Maintenance_Selected
0,TX_1,2845,5860,27842,7406,32,1344,16684,5467,7,...,90000,16,4,90000,16,4,90000,16,4,1
1,TX_16,13200,1120,32800,2650,156,2240,16400,1610,1510,...,90000,16,4,90000,16,4,90000,16,4,1
2,TX_14,23349,2475,28011,5045,156,48,5588,3532,2951,...,90000,16,4,90000,16,4,90000,16,4,1
3,TX_41,3060,257,69500,190,403,8930,68,47,0,...,50000,8,3,50000,8,3,50000,8,3,1
4,TX_24,106,581,75200,47,760,4070,11,30,0,...,20000,3,2,20000,3,2,20000,3,2,1

### _Resource Utilization_

In [83]:
total_priority = maintenance_schedule["Priority_Score"].sum()
total_cost = maintenance_schedule["Maintenance_Cost"].sum()
total_hours = maintenance_schedule["Maintenance_Hours"].sum()
total_crew = maintenance_schedule["Crew_Required"].sum()

print("=" * 50)

print(f"Transformers Selected : {len(maintenance_schedule)}")
print(f"Total Priority Score  : {total_priority:.2f}")
print(f"Budget Utilized       : ₹{total_cost:,.0f}")
print(f"Hours Utilized        : {total_hours}")
print(f"Crew Utilized         : {total_crew}")

print("=" * 50)

==================================================
Transformers Selected : 5
Total Priority Score  : 267.94
Budget Utilized       : ₹340,000
Hours Utilized        : 59
Crew Utilized         : 17
==================================================

### _Verify Constraints_

In [84]:
print("Constraint Verification")
print("-" * 40)

print(f"Budget Used : ₹{total_cost:,.0f} / ₹{MAINTENANCE_BUDGET:,.0f}")
print(f"Hours Used  : {total_hours} / {AVAILABLE_HOURS}")
print(f"Crew Used   : {total_crew} / {AVAILABLE_CREW}")

Constraint Verification
----------------------------------------
Budget Used : ₹340,000 / ₹350,000
Hours Used  : 59 / 70
Crew Used   : 17 / 17

### _Optimal Maintenance Schedule_

_The table below lists the transformers selected by the optimization model for maintenance.
The transformers are ranked according to their maintenance priority score, where a higher priority score indicates a greater need for maintenance intervention._

In [85]:
maintenance_schedule = (
    optimization_df[
        optimization_df["Maintenance_Selected"] == 1
    ].sort_values(
        by="Priority_Score",
        ascending=False
    ).reset_index(drop=True)
)

maintenance_schedule[
    [
        "Transformer_ID",
        "Predicted_Health_Index",
        "Predicted_Health_Category",
        "Priority_Score",
        "Maintenance_Cost",
        "Maintenance_Hours",
        "Crew_Required"
    ]
]

,Transformer_ID,Predicted_Health_Index,Predicted_Health_Category,Priority_Score,Maintenance_Cost,Maintenance_Hours,Crew_Required
0,TX_1,30.00,Poor,70.67,90000,16,4
1,TX_16,30.00,Poor,69.06,90000,16,4
2,TX_14,30.00,Poor,66.79,90000,16,4
3,TX_41,55.88,Fair,37.60,50000,8,3
4,TX_24,76.19,Good,23.82,20000,3,2